import type { Metadata } from "next";
import "./globals.css";

import { Nunito } from "next/font/google";
import Navbar from "@/components/layout/ navbar";
import ChatProvider from "@/modules/chat/providers";

import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Roomly app",
  description: "Generated by create next app",
};

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <ChatProvider>
          <Navbar />
          {children}
          <Toaster />
        </ChatProvider>
      </body>
    </html>
  );
}
